<H2> Capstone Project - The Battle of the Neighborhoods (Week 2)</H2>

<H3>Applied Data Science Capstone by IBM/Coursera</H3>

<B> Table of Contents </B>

* [Introduction: Business Problem](#introduction)
* [Data](#data)
* [Analysis](#analysis)
* [Results and Discussion](#discussion)
* [Conclusion](#conclusion)

<B><font color = 'blue'> Introduction: Business Problem </font><a name="introduction"></a> </B>

In this project we will compare the top 5 drinking locations in New York City (NYC) to Toronto. Specifically, this report will be targeted to stakeholders interested in drinking places in NYC versus Toronto to determine which city has better drinks.

Only the top 5 drinking places will be considered for each city. The data will be scraped from Foursquare and will be sort by popularity. Data to consider assessing will include price, rating and number of likes. Additional unique features may also be taken into consideration. <BR><BR>

<B><font color = 'blue'> Data </font><a name="data"></a> </B>

Based on our defined business problem, factors that will influence our decisions are:
* Price
* Rating
* Number of Likes
* Unique features if any
<BR>

In [7]:
#Import the needed libraries
import requests 
import pandas as pd 
import numpy as np 
import random 
!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim 

from IPython.display import Image 
from IPython.core.display import HTML 
    
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

print('Folium installed')
print('Libraries imported.')

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Folium installed
Libraries imported.

In [12]:
CLIENT_ID = '1DMKQ5NQ5VMJLWX5GSWMA0HGJCXJMWBKY3GURRVXVD3MQMLW' 
CLIENT_SECRET = 'OFVFGV1NCWSYF5X5B0S4ZTJYE4GPK4FYOX2MYJ1AV1NAUNUU'
VERSION = '20180604'
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 1DMKQ5NQ5VMJLWX5GSWMA0HGJCXJMWBKY3GURRVXVD3MQMLW
CLIENT_SECRET:OFVFGV1NCWSYF5X5B0S4ZTJYE4GPK4FYOX2MYJ1AV1NAUNUU

In [8]:
geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode('New York City, NY')
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

40.7127281 -74.0060152

In [9]:
radius = 500

In [13]:
nyc_drinks_url = 'https://api.foursquare.com/v2/venues/explore?ll=40.7127281,-74.0060152&section=drinks&sortByPopularity=0&limit=5&client_id={}&client_secret={}&v={}&radius={}'.format(CLIENT_ID, CLIENT_SECRET, VERSION, radius)
nyc_drinks_result = requests.get(nyc_drinks_url).json()
nyc_drinks_result

{'meta': {'code': 200, 'requestId': '5e33813db57e88001bf54b50'},
 'response': {'suggestedFilters': {'header': 'Tap to show:',
   'filters': [{'name': '$-$$$$', 'key': 'price'},
    {'name': 'Open now', 'key': 'openNow'}]},
  'headerLocation': 'Downtown Manhattan',
  'headerFullLocation': 'Downtown Manhattan, New York',
  'headerLocationGranularity': 'neighborhood',
  'query': 'drinks',
  'totalResults': 41,
  'suggestedBounds': {'ne': {'lat': 40.7172281045, 'lng': -74.00008952063419},
   'sw': {'lat': 40.7082280955, 'lng': -74.0119408793658}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '57f0689d498e7d49d9189369',
       'name': 'The Bar Room at Temple Court',
       'location': {'address': '123 Nassau St',
        'lat': 40.7114477287544,
        'lng': -74.00680157032005,
        'labeledLatLngs': [{'label': 'display',
          'lat': 40.7114477287544,
          'lng': -74.00680157032005}],
        'distance': 157,
        'postalCode': '10038',
        'cc': 'US',
        'neighborhood': 'Financial District',
        'city': 'New York',
        'state': 'NY',
        'country': 'United States',
        'formattedAddress': ['123 Nassau St',
         'New York, NY 10038',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d1d5941735',
         'name': 'Hotel Bar',
         'pluralName': 'Hotel Bars',
         'shortName': 'Hotel Bar',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/travel/hotel_bar_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-4-57f0689d498e7d49d9189369-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '534c9d7b498e1bdd443a40e1',
       'name': 'Racines',
       'location': {'address': '94 Chambers St',
        'lat': 40.714754151461236,
        'lng': -74.0075806002039,
        'labeledLatLngs': [{'label': 'display',
          'lat': 40.714754151461236,
          'lng': -74.0075806002039}],
        'distance': 261,
        'postalCode': '10007',
        'cc': 'US',
        'city': 'New York',
        'state': 'NY',
        'country': 'United States',
        'formattedAddress': ['94 Chambers St',
         'New York, NY 10007',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d10c941735',
         'name': 'French Restaurant',
         'pluralName': 'French Restaurants',
         'shortName': 'French',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/french_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-4-534c9d7b498e1bdd443a40e1-1'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4db5fbfe43a1369cb5dc2a1f',
       'name': "Maxwell's Bar & Restaurant",
       'location': {'address': '59 Reade St',
        'crossStreet': 'at Broadway',
        'lat': 40.71494392643706,
        'lng': -74.00648461952706,
        'labeledLatLngs': [{'label': 'display',
          'lat': 40.71494392643706,
          'lng': -74.00648461952706}],
        'distance': 249,
        'postalCode': '10007',
        'cc': 'US',
        'city': 'New York',
        'state': 'NY',
        'country': 'United States',
        'formattedAddress': ['59 Reade St (at Broadway)',
         'New York, NY 10007',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d116941735',
         'name': 'Bar',
         'pluralName': 'Bars',
         'shortName': 'Bar',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/pub_',
          'suffix': '.png'},
         'primary': True}],
       'delivery': {'id': '315611',
        'url': 'https://www.seamless.com/menu/maxwells-59-reade-st-new-york/315611?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=315611',
        'provider': {'name': 'seamless',
         'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
          'sizes': [40, 50],
          'name': '/delivery_provider_seamless_20180129.png'}}},
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '45470725'}},
      'referralId': 'e-4-4db5fbfe43a1369cb5dc2a1f-2'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4aa0669cf964a5207e3f20e3',
       'name': 'The Wooly',
       'location': {'address': '11 Barclay St',
        'crossStreet': 'at Broadway',
        'lat': 40.712212455153555,
        'lng': -74.00835715252087,
        'labeledLatLngs': [{'label': 'display',
          'lat': 40.712212455153555,
          'lng': -74.00835715252087}],
        'distance': 205,
        'postalCode': '10279',
        'cc': 'US',
        'city': 'New York',
        'state': 'NY',
        'country': 'United States',
        'formattedAddress': ['11 Barclay St (at Broadway)',
         'New York, NY 10279',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d171941735',
         'name': 'Event Space',
         'pluralName': 'Event Spaces',
         'shortName': 'Event Space',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/building/eventspace_',
          'suffix': '.png'},
         'primary': True}],
       'delivery': {'id': '1085252',
        'url': 'https://www.grubhub.com/restaurant/the-wooly-public-233-broadway-new-york/1085252?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=1085252',
        'provider': {'name': 'grubhub',
         'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
          'sizes': [40, 50],
          'name': '/delivery_provider_grubhub_20180129.png'}}},
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '82838739'}},
      'referralId': 'e-4-4aa0669cf964a5207e3f20e3-3'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '433b2e80f964a52036281fe3',
       'name': 'FlashDancers Downtown',
       'location': {'address': '59 Murray St',
        'crossStreet': 'Church St & West Broadway',
        'lat': 40.71435,
        'lng': -74.0098,
        'labeledLatLngs': [{'label': 'display',
          'lat': 40.71435,
          'lng': -74.0098}],
        'distance': 366,
        'postalCode': '10007',
        'cc': 'US',
        'city': 'New York',
        'state': 'NY',
        'country': 'United States',
        'formattedAddress': ['59 Murray St (Church St & West Broadway)',
         'New York, NY 10007',
         'United States']},
       'categories': [{'id': '4bf58dd8d48988d1d6941735',
         'name': 'Strip Club',
         'pluralName': 'Strip Clubs',
         'shortName': 'Strip Club',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/stripclub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '79597613'}},
      'referralId': 'e-4-433b2e80f964a52036281fe3-4'}]}]}}

In [14]:
nyc_venue = nyc_drinks_result['response']['groups'][0]['items']
nyc_drinks_df = json_normalize(nyc_venue)
nyc_drinks_df

,referralId,reasons.count,reasons.items,venue.id,venue.name,venue.location.address,venue.location.lat,venue.location.lng,venue.location.labeledLatLngs,venue.location.distance,...,venue.photos.count,venue.photos.groups,venue.location.crossStreet,venue.delivery.id,venue.delivery.url,venue.delivery.provider.name,venue.delivery.provider.icon.prefix,venue.delivery.provider.icon.sizes,venue.delivery.provider.icon.name,venue.venuePage.id
0,e-4-57f0689d498e7d49d9189369-0,0,"[{'summary': 'This spot is popular', 'type': '...",57f0689d498e7d49d9189369,The Bar Room at Temple Court,123 Nassau St,40.711448,-74.006802,"[{'label': 'display', 'lat': 40.7114477287544,...",157,...,0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,e-4-534c9d7b498e1bdd443a40e1-1,0,"[{'summary': 'This spot is popular', 'type': '...",534c9d7b498e1bdd443a40e1,Racines,94 Chambers St,40.714754,-74.007581,"[{'label': 'display', 'lat': 40.71475415146123...",261,...,0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,e-4-4db5fbfe43a1369cb5dc2a1f-2,0,"[{'summary': 'This spot is popular', 'type': '...",4db5fbfe43a1369cb5dc2a1f,Maxwell's Bar & Restaurant,59 Reade St,40.714944,-74.006485,"[{'label': 'display', 'lat': 40.71494392643706...",249,...,0,[],at Broadway,315611,https://www.seamless.com/menu/maxwells-59-read...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png,45470725
3,e-4-4aa0669cf964a5207e3f20e3-3,0,"[{'summary': 'This spot is popular', 'type': '...",4aa0669cf964a5207e3f20e3,The Wooly,11 Barclay St,40.712212,-74.008357,"[{'label': 'display', 'lat': 40.71221245515355...",205,...,0,[],at Broadway,1085252,https://www.grubhub.com/restaurant/the-wooly-p...,grubhub,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_grubhub_20180129.png,82838739
4,e-4-433b2e80f964a52036281fe3-4,0,"[{'summary': 'This spot is popular', 'type': '...",433b2e80f964a52036281fe3,FlashDancers Downtown,59 Murray St,40.714350,-74.009800,"[{'label': 'display', 'lat': 40.71435, 'lng': ...",366,...,0,[],Church St & West Broadway,NaN,NaN,NaN,NaN,NaN,NaN,79597613

In [15]:
#overviewing the columns to see if there are unique features we can pull
list(nyc_drinks_df.columns)

['referralId',
 'reasons.count',
 'reasons.items',
 'venue.id',
 'venue.name',
 'venue.location.address',
 'venue.location.lat',
 'venue.location.lng',
 'venue.location.labeledLatLngs',
 'venue.location.distance',
 'venue.location.postalCode',
 'venue.location.cc',
 'venue.location.neighborhood',
 'venue.location.city',
 'venue.location.state',
 'venue.location.country',
 'venue.location.formattedAddress',
 'venue.categories',
 'venue.photos.count',
 'venue.photos.groups',
 'venue.location.crossStreet',
 'venue.delivery.id',
 'venue.delivery.url',
 'venue.delivery.provider.name',
 'venue.delivery.provider.icon.prefix',
 'venue.delivery.provider.icon.sizes',
 'venue.delivery.provider.icon.name',
 'venue.venuePage.id']

In [16]:
nyc_drinks2_df = nyc_drinks_df[['venue.id','venue.name','venue.location.lat', 'venue.location.lng', 'venue.location.formattedAddress', 'venue.delivery.url']]
nyc_drinks2_df

,venue.id,venue.name,venue.location.lat,venue.location.lng,venue.location.formattedAddress,venue.delivery.url
0,57f0689d498e7d49d9189369,The Bar Room at Temple Court,40.711448,-74.006802,"[123 Nassau St, New York, NY 10038, United Sta...",NaN
1,534c9d7b498e1bdd443a40e1,Racines,40.714754,-74.007581,"[94 Chambers St, New York, NY 10007, United St...",NaN
2,4db5fbfe43a1369cb5dc2a1f,Maxwell's Bar & Restaurant,40.714944,-74.006485,"[59 Reade St (at Broadway), New York, NY 10007...",https://www.seamless.com/menu/maxwells-59-read...
3,4aa0669cf964a5207e3f20e3,The Wooly,40.712212,-74.008357,"[11 Barclay St (at Broadway), New York, NY 102...",https://www.grubhub.com/restaurant/the-wooly-p...
4,433b2e80f964a52036281fe3,FlashDancers Downtown,40.714350,-74.009800,"[59 Murray St (Church St & West Broadway), New...",NaN

In [17]:
nyc_venues_id_list = nyc_drinks_df['venue.id'].values.tolist()
nyc_venues_id_list

['57f0689d498e7d49d9189369',
 '534c9d7b498e1bdd443a40e1',
 '4db5fbfe43a1369cb5dc2a1f',
 '4aa0669cf964a5207e3f20e3',
 '433b2e80f964a52036281fe3']

In [18]:
nyc_rating = []
nyc_price = []
nyc_likes = []

for nyc_venues1 in nyc_venues_id_list:
    url2 = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(nyc_venues1, CLIENT_ID, CLIENT_SECRET, VERSION)
    result2 = requests.get(url2).json()
    result4 = result2['response']['venue']['rating']
    result5 = result2['response']['venue']['attributes']['groups'][0]['summary']
    result6 = result2['response']['venue']['likes']['count']
    nyc_rating.append(result4)
    nyc_price.append(result5)
    nyc_likes.append(result6)

nyc_rpl = pd.DataFrame({'Price': nyc_price, 'Rating': nyc_rating, 'Number of likes': nyc_likes})
nyc_rpl

  Price  Rating  Number of likes
0   $$$     9.4              182
1   $$$     8.6              115
2    $$     8.1              165
3   $$$     7.8              173
4   $$$     8.7               87

In [19]:
nyc_v1 = pd.concat([nyc_drinks2_df, nyc_rpl], axis=1)
nyc_v1

,venue.id,venue.name,venue.location.lat,venue.location.lng,venue.location.formattedAddress,venue.delivery.url,Price,Rating,Number of likes
0,57f0689d498e7d49d9189369,The Bar Room at Temple Court,40.711448,-74.006802,"[123 Nassau St, New York, NY 10038, United Sta...",NaN,$$$,9.4,182
1,534c9d7b498e1bdd443a40e1,Racines,40.714754,-74.007581,"[94 Chambers St, New York, NY 10007, United St...",NaN,$$$,8.6,115
2,4db5fbfe43a1369cb5dc2a1f,Maxwell's Bar & Restaurant,40.714944,-74.006485,"[59 Reade St (at Broadway), New York, NY 10007...",https://www.seamless.com/menu/maxwells-59-read...,$$,8.1,165
3,4aa0669cf964a5207e3f20e3,The Wooly,40.712212,-74.008357,"[11 Barclay St (at Broadway), New York, NY 102...",https://www.grubhub.com/restaurant/the-wooly-p...,$$$,7.8,173
4,433b2e80f964a52036281fe3,FlashDancers Downtown,40.714350,-74.009800,"[59 Murray St (Church St & West Broadway), New...",NaN,$$$,8.7,87

In [20]:
#renaming columns and replacing NaN values
nyc_v2 = nyc_v1.rename(columns={"venue.id": "ID", "venue.name": "Venue", "venue.location.lat": "Latitude", "venue.location.lng": "Longitude", "venue.location.formattedAddress": "Address", "venue.delivery.url": "Delivery url"})
nyc_v2.fillna("Not available", inplace = True)

In [22]:
#price range per Foursquare
nyc_v3 = nyc_v2.replace({'$$': '$10-$20', '$$$':'$20-$30'})

In [23]:
geolocator2 = Nominatim(user_agent="foursquare_agent")
location2 = geolocator2.geocode('Toronto, ON')
latitude2 = location2.latitude
longitude2 = location2.longitude
print(latitude2, longitude2)

43.653963 -79.387207

In [24]:
toronto_drinks_url = 'https://api.foursquare.com/v2/venues/explore?ll=43.653963,-79.387207&section=drinks&sortByPopularity=0&limit=5&client_id={}&client_secret={}&v={}&radius={}'.format(CLIENT_ID, CLIENT_SECRET, VERSION, radius)
toronto_drinks_result = requests.get(toronto_drinks_url).json()
toronto_drinks_result

{'meta': {'code': 200, 'requestId': '5e3382320de0d9001b1aaa1a'},
 'response': {'suggestedFilters': {'header': 'Tap to show:',
   'filters': [{'name': 'Open now', 'key': 'openNow'}]},
  'headerLocation': 'Bay Street Corridor',
  'headerFullLocation': 'Bay Street Corridor, Toronto',
  'headerLocationGranularity': 'neighborhood',
  'query': 'drinks',
  'totalResults': 13,
  'suggestedBounds': {'ne': {'lat': 43.6584630045, 'lng': -79.38099903084075},
   'sw': {'lat': 43.649462995499995, 'lng': -79.39341496915925}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ad7bf71f964a5205b0e21e3',
       'name': 'Sin and Redemption',
       'location': {'address': '136 McCaul St.',
        'crossStreet': 'at Dundas St.',
        'lat': 43.65466135819523,
        'lng': -79.39173728227614,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.65466135819523,
          'lng': -79.39173728227614}],
        'distance': 373,
        'postalCode': 'M5T 1W2',
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['136 McCaul St. (at Dundas St.)',
         'Toronto ON M5T 1W2',
         'Canada']},
       'categories': [{'id': '4bf58dd8d48988d116941735',
         'name': 'Bar',
         'pluralName': 'Bars',
         'shortName': 'Bar',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/pub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-4-4ad7bf71f964a5205b0e21e3-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ab2b0b9f964a520e56b20e3',
       'name': 'The Queen and Beaver Public House',
       'location': {'address': '35 Elm St.',
        'crossStreet': 'at Bay St.',
        'lat': 43.65747228208784,
        'lng': -79.38352412327917,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.65747228208784,
          'lng': -79.38352412327917}],
        'distance': 490,
        'postalCode': 'M5G 1H1',
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['35 Elm St. (at Bay St.)',
         'Toronto ON M5G 1H1',
         'Canada']},
       'categories': [{'id': '4bf58dd8d48988d155941735',
         'name': 'Gastropub',
         'pluralName': 'Gastropubs',
         'shortName': 'Gastropub',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/gastropub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-4-4ab2b0b9f964a520e56b20e3-1'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '5a17736b446ea613107b50ce',
       'name': 'Suite 114',
       'location': {'address': '116 Dundas St W',
        'lat': 43.655766,
        'lng': -79.38431,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.655766,
          'lng': -79.38431}],
        'distance': 307,
        'postalCode': 'M5G 1C3',
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['116 Dundas St W',
         'Toronto ON M5G 1C3',
         'Canada']},
       'categories': [{'id': '4bf58dd8d48988d1d4941735',
         'name': 'Speakeasy',
         'pluralName': 'Speakeasies',
         'shortName': 'Speakeasy',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/secretbar_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-4-5a17736b446ea613107b50ce-2'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4c3a8e78be4620a1c6180b13',
       'name': 'Hilton Toronto Executive Lounge',
       'location': {'address': '145 Richmond Street West',
        'lat': 43.650363125865155,
        'lng': -79.38580184119992,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.650363125865155,
          'lng': -79.38580184119992}],
        'distance': 416,
        'postalCode': 'M5G 1Y1',
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['145 Richmond Street West',
         'Toronto ON M5G 1Y1',
         'Canada']},
       'categories': [{'id': '4bf58dd8d48988d143941735',
         'name': 'Breakfast Spot',
         'pluralName': 'Breakfast Spots',
         'shortName': 'Breakfast',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/breakfast_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-4-4c3a8e78be4620a1c6180b13-3'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '549dd93f498eec33464a5fd2',
       'name': 'Queen St. Warehouse',
       'location': {'address': '232 Queen St W',
        'crossStreet': 'John St',
        'lat': 43.650116540590425,
        'lng': -79.3903160886256,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.650116540590425,
          'lng': -79.3903160886256}],
        'distance': 496,
        'postalCode': 'M5V 1Z6',
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['232 Queen St W (John St)',
         'Toronto ON M5V 1Z6',
         'Canada']},
       'categories': [{'id': '4bf58dd8d48988d116941735',
         'name': 'Bar',
         'pluralName': 'Bars',
         'shortName': 'Bar',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/pub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-4-549dd93f498eec33464a5fd2-4'}]}]}}

In [25]:
toronto_venue = toronto_drinks_result['response']['groups'][0]['items']
toronto_drinks_df = json_normalize(toronto_venue)

toronto_drinks_df

,referralId,reasons.count,reasons.items,venue.id,venue.name,venue.location.address,venue.location.crossStreet,venue.location.lat,venue.location.lng,venue.location.labeledLatLngs,venue.location.distance,venue.location.postalCode,venue.location.cc,venue.location.city,venue.location.state,venue.location.country,venue.location.formattedAddress,venue.categories,venue.photos.count,venue.photos.groups
0,e-4-4ad7bf71f964a5205b0e21e3-0,0,"[{'summary': 'This spot is popular', 'type': '...",4ad7bf71f964a5205b0e21e3,Sin and Redemption,136 McCaul St.,at Dundas St.,43.654661,-79.391737,"[{'label': 'display', 'lat': 43.65466135819523...",373,M5T 1W2,CA,Toronto,ON,Canada,"[136 McCaul St. (at Dundas St.), Toronto ON M5...","[{'id': '4bf58dd8d48988d116941735', 'name': 'B...",0,[]
1,e-4-4ab2b0b9f964a520e56b20e3-1,0,"[{'summary': 'This spot is popular', 'type': '...",4ab2b0b9f964a520e56b20e3,The Queen and Beaver Public House,35 Elm St.,at Bay St.,43.657472,-79.383524,"[{'label': 'display', 'lat': 43.65747228208784...",490,M5G 1H1,CA,Toronto,ON,Canada,"[35 Elm St. (at Bay St.), Toronto ON M5G 1H1, ...","[{'id': '4bf58dd8d48988d155941735', 'name': 'G...",0,[]
2,e-4-5a17736b446ea613107b50ce-2,0,"[{'summary': 'This spot is popular', 'type': '...",5a17736b446ea613107b50ce,Suite 114,116 Dundas St W,NaN,43.655766,-79.384310,"[{'label': 'display', 'lat': 43.655766, 'lng':...",307,M5G 1C3,CA,Toronto,ON,Canada,"[116 Dundas St W, Toronto ON M5G 1C3, Canada]","[{'id': '4bf58dd8d48988d1d4941735', 'name': 'S...",0,[]
3,e-4-4c3a8e78be4620a1c6180b13-3,0,"[{'summary': 'This spot is popular', 'type': '...",4c3a8e78be4620a1c6180b13,Hilton Toronto Executive Lounge,145 Richmond Street West,NaN,43.650363,-79.385802,"[{'label': 'display', 'lat': 43.65036312586515...",416,M5G 1Y1,CA,Toronto,ON,Canada,"[145 Richmond Street West, Toronto ON M5G 1Y1,...","[{'id': '4bf58dd8d48988d143941735', 'name': 'B...",0,[]
4,e-4-549dd93f498eec33464a5fd2-4,0,"[{'summary': 'This spot is popular', 'type': '...",549dd93f498eec33464a5fd2,Queen St. Warehouse,232 Queen St W,John St,43.650117,-79.390316,"[{'label': 'display', 'lat': 43.65011654059042...",496,M5V 1Z6,CA,Toronto,ON,Canada,"[232 Queen St W (John St), Toronto ON M5V 1Z6,...","[{'id': '4bf58dd8d48988d116941735', 'name': 'B...",0,[]

In [26]:
list(toronto_drinks_df.columns)

['referralId',
 'reasons.count',
 'reasons.items',
 'venue.id',
 'venue.name',
 'venue.location.address',
 'venue.location.crossStreet',
 'venue.location.lat',
 'venue.location.lng',
 'venue.location.labeledLatLngs',
 'venue.location.distance',
 'venue.location.postalCode',
 'venue.location.cc',
 'venue.location.city',
 'venue.location.state',
 'venue.location.country',
 'venue.location.formattedAddress',
 'venue.categories',
 'venue.photos.count',
 'venue.photos.groups']

In [27]:
toronto_drinks2_df = toronto_drinks_df[['venue.id','venue.name','venue.location.lat', 'venue.location.lng', 'venue.location.formattedAddress']]
toronto_drinks2_df

,venue.id,venue.name,venue.location.lat,venue.location.lng,venue.location.formattedAddress
0,4ad7bf71f964a5205b0e21e3,Sin and Redemption,43.654661,-79.391737,"[136 McCaul St. (at Dundas St.), Toronto ON M5..."
1,4ab2b0b9f964a520e56b20e3,The Queen and Beaver Public House,43.657472,-79.383524,"[35 Elm St. (at Bay St.), Toronto ON M5G 1H1, ..."
2,5a17736b446ea613107b50ce,Suite 114,43.655766,-79.384310,"[116 Dundas St W, Toronto ON M5G 1C3, Canada]"
3,4c3a8e78be4620a1c6180b13,Hilton Toronto Executive Lounge,43.650363,-79.385802,"[145 Richmond Street West, Toronto ON M5G 1Y1,..."
4,549dd93f498eec33464a5fd2,Queen St. Warehouse,43.650117,-79.390316,"[232 Queen St W (John St), Toronto ON M5V 1Z6,..."

In [28]:
toronto_venues_id_list = toronto_drinks2_df['venue.id'].values.tolist()
toronto_venues_id_list

['4ad7bf71f964a5205b0e21e3',
 '4ab2b0b9f964a520e56b20e3',
 '5a17736b446ea613107b50ce',
 '4c3a8e78be4620a1c6180b13',
 '549dd93f498eec33464a5fd2']

In [29]:
toronto_rating = []
toronto_price = []
toronto_likes = []

for toronto_venues1 in toronto_venues_id_list:
    url_t2 = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(toronto_venues1, CLIENT_ID, CLIENT_SECRET, VERSION)
    result_t2 = requests.get(url_t2).json()
    result_t4 = result_t2['response']['venue']['rating']
    result_t5 = result_t2['response']['venue']['attributes']['groups'][0]['summary']
    result_t6 = result_t2['response']['venue']['likes']['count']
    toronto_rating.append(result_t4)
    toronto_price.append(result_t5)
    toronto_likes.append(result_t6)

toronto_rpl = pd.DataFrame({'Price': toronto_price, 'Rating': toronto_rating, 'Number of likes': toronto_likes})
toronto_rpl

  Price  Rating  Number of likes
0    $$     8.0              153
1    $$     8.5              233
2   $$$     7.5                6
3   $$$     7.8               29
4    $$     7.9              122

In [30]:
toronto_v1 = pd.concat([toronto_drinks2_df, toronto_rpl], axis=1)
toronto_v1

,venue.id,venue.name,venue.location.lat,venue.location.lng,venue.location.formattedAddress,Price,Rating,Number of likes
0,4ad7bf71f964a5205b0e21e3,Sin and Redemption,43.654661,-79.391737,"[136 McCaul St. (at Dundas St.), Toronto ON M5...",$$,8.0,153
1,4ab2b0b9f964a520e56b20e3,The Queen and Beaver Public House,43.657472,-79.383524,"[35 Elm St. (at Bay St.), Toronto ON M5G 1H1, ...",$$,8.5,233
2,5a17736b446ea613107b50ce,Suite 114,43.655766,-79.384310,"[116 Dundas St W, Toronto ON M5G 1C3, Canada]",$$$,7.5,6
3,4c3a8e78be4620a1c6180b13,Hilton Toronto Executive Lounge,43.650363,-79.385802,"[145 Richmond Street West, Toronto ON M5G 1Y1,...",$$$,7.8,29
4,549dd93f498eec33464a5fd2,Queen St. Warehouse,43.650117,-79.390316,"[232 Queen St W (John St), Toronto ON M5V 1Z6,...",$$,7.9,122

In [31]:
toronto_v2 = toronto_v1.rename(columns={"venue.id": "ID", "venue.name": "Venue", "venue.location.lat": "Latitude", "venue.location.lng": "Longitude", "venue.location.formattedAddress": "Address"})

In [32]:
toronto_v3 = toronto_v2.replace({'$$': '$10-$20', '$$$':'$20-$30'})

<BR><BR><B><font color = 'blue'> Data </font><a name="data"></B> </H3>

<B> NEW YORK CITY </B>

In [35]:
nyc_v3

,ID,Venue,Latitude,Longitude,Address,Delivery url,Price,Rating,Number of likes
0,57f0689d498e7d49d9189369,The Bar Room at Temple Court,40.711448,-74.006802,"[123 Nassau St, New York, NY 10038, United Sta...",Not available,$20-$30,9.4,182
1,534c9d7b498e1bdd443a40e1,Racines,40.714754,-74.007581,"[94 Chambers St, New York, NY 10007, United St...",Not available,$20-$30,8.6,115
2,4db5fbfe43a1369cb5dc2a1f,Maxwell's Bar & Restaurant,40.714944,-74.006485,"[59 Reade St (at Broadway), New York, NY 10007...",https://www.seamless.com/menu/maxwells-59-read...,$10-$20,8.1,165
3,4aa0669cf964a5207e3f20e3,The Wooly,40.712212,-74.008357,"[11 Barclay St (at Broadway), New York, NY 102...",https://www.grubhub.com/restaurant/the-wooly-p...,$20-$30,7.8,173
4,433b2e80f964a52036281fe3,FlashDancers Downtown,40.714350,-74.009800,"[59 Murray St (Church St & West Broadway), New...",Not available,$20-$30,8.7,87

In [39]:
nyc_map = folium.Map(location=[latitude, longitude], zoom_start=15)

for lat, lng in zip(nyc_v3.Latitude, nyc_v3.Longitude):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(nyc_map)

nyc_map

<B> TORONTO </B>

In [36]:
toronto_v3

,ID,Venue,Latitude,Longitude,Address,Price,Rating,Number of likes
0,4ad7bf71f964a5205b0e21e3,Sin and Redemption,43.654661,-79.391737,"[136 McCaul St. (at Dundas St.), Toronto ON M5...",$10-$20,8.0,153
1,4ab2b0b9f964a520e56b20e3,The Queen and Beaver Public House,43.657472,-79.383524,"[35 Elm St. (at Bay St.), Toronto ON M5G 1H1, ...",$10-$20,8.5,233
2,5a17736b446ea613107b50ce,Suite 114,43.655766,-79.384310,"[116 Dundas St W, Toronto ON M5G 1C3, Canada]",$20-$30,7.5,6
3,4c3a8e78be4620a1c6180b13,Hilton Toronto Executive Lounge,43.650363,-79.385802,"[145 Richmond Street West, Toronto ON M5G 1Y1,...",$20-$30,7.8,29
4,549dd93f498eec33464a5fd2,Queen St. Warehouse,43.650117,-79.390316,"[232 Queen St W (John St), Toronto ON M5V 1Z6,...",$10-$20,7.9,122

In [41]:
toronto_map = folium.Map(location=[43.653963, -79.387207], zoom_start=15)

for lat, lng in zip(toronto_v3.Latitude, toronto_v3.Longitude):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='red',
        fill = True,
        fill_color='red',
        fill_opacity=0.6
    ).add_to(toronto_map)

toronto_map

<BR><BR><B><font color = 'blue'> Results and Discussion </font><a name="discussion"></B>

Our data shows that NYC has higher ratings and also pricier.

The rating for NYC range from 7.8 to 9.4. Only one of the five venue is tier price 2 (\\$10 - \\$20) and the rest are tier price 3 (\\$20 - \\$30). Although Flash Dancers Downtown has the second highest rating of 8.7, note that there are only 87 likes. Interestingly, two of the venues have delivery, however it is most likely related to food and not drinks. 

The rating for Toronto range from 7.5 to 8.0. Three of the venues are tier price 2 and the other two are tier price 3. Interestingly, Suite 114 and Hilton Toronto Executive Lounge only has 6 and 29 likes respectively. The other three venues have more likes, indicating a better data population.

<U> Analysis </U><BR>
Overall, it is difficult to make the comparison between drinking venues in NYC and Toronto just based on price, ratings and likes. The reasons include the following:
* The number of customers is different, therefore the data population may be skewed. 
* Some venues seem to offer both drinks and food - which makes it difficult to understand if it is the food that was rated high or the drinks. 
* Different venue offer different menu, a deeper look into the menu may offer more valuable insights
* Further scraping on the comments/reviews per venue may offer more insights into customer taste
    
In addition, I find it interesting how Foursquare have sorted the venues popularity. While the url was set to 'sortByPopularity=0', the data generated did not sort the ratings from high to low. The sort by popularity could also be set to 1, which I tried as an experiment and it yielded lower number of likes therefore I decided to keep it at zero. Understanding how Foursquare sorted the venues would be crucial to have better confidence if the venues generated were indeed the top venues.

<BR><BR><B><font color = 'blue'> Conclusion </font><a name="conclusion"></B>

While the data was inconclusive, we can agree that NYC is more popular due to more number of likes. More data scraping would be required to further determine the differences for customers to determine which city would be a better fit for them.